/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package entities;


rule "PhenotypeA Severity1 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'A', severityLevel == 1)
    then 
        p.setSuggestedTreatment("SABA / SAMA or LAMA / LABA");
end

rule "PhenotypeA Severity2 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'A', severityLevel == 2)
    then 
        p.setSuggestedTreatment("LAMA / LABA or LAMA + LABA");
end

rule "PhenotypeA Severity3 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'A', severityLevel == 3)
    then 
        p.setSuggestedTreatment("LAMA + LABA");
end

rule "PhenotypeA Severity4 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'A', severityLevel == 4)
    then 
        p.setSuggestedTreatment("LAMA + LABA or LAMA + LABA + Teofiline");
end

rule "PhenotypeB Severity1 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'B', severityLevel == 1)
    then 
        p.setSuggestedTreatment("LABA + CI");
end

rule "PhenotypeB Severity2 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'B', severityLevel == 2)
    then 
        p.setSuggestedTreatment("LABA + CI");
end

rule "PhenotypeB Severity3 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'B', severityLevel == 3)
    then 
        p.setSuggestedTreatment("LAMA + LABA + CI");
end

rule "PhenotypeB Severity4 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'B', severityLevel == 4)
    then 
        p.setSuggestedTreatment("LAMA + LABA + CI, Consider adding Teofiline/IPE4 with expectoration");
end

rule "PhenotypeC Severity1 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'C', severityLevel == 1)
    then 
        p.setSuggestedTreatment("LAMA / LABA");
end

rule "PhenotypeC Severity2 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'C', severityLevel == 2)
    then 
        p.setSuggestedTreatment("(LAMA / LABA) + CI or LAMA + LABA or LAMA/LABA");
end

rule "PhenotypeC Severity3 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'C', severityLevel == 3)
    then 
        p.setSuggestedTreatment("LAMA + LABA + CI");
end

rule "PhenotypeC Severity4 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'C', severityLevel == 4)
    then 
        p.setSuggestedTreatment("LAMA + LABA + CI, Consider adding Teofiline");
end

rule "PhenotypeD Severity1 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'D', severityLevel == 1)
    then 
        p.setSuggestedTreatment("LAMA / LABA");
end

rule "PhenotypeD Severity2 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'D', severityLevel == 2)
    then 
        p.setSuggestedTreatment("(LAMA / LABA) + (CI / IPE4) or LAMA + LABA or  LAMA / LABA");
end

rule "PhenotypeD Severity3 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'D', severityLevel == 3)
    then 
        p.setSuggestedTreatment("LAMA + LABA + (CI / IPE4) or (LAMA / LABA) + CI + IPE4, and consider adding Carbocisteine");
end

rule "PhenotypeD Severity4 Rule"
    dialect "java"
    when
        p : Patient (phenotype == 'D', severityLevel == 4)
    then 
        p.setSuggestedTreatment("LAMA + LABA + (CI / IPE4) or LAMA + LABA + CI + IPE4, and consider adding Carbocisteine/Antibiotics");
end