/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package entities;

unit MedicalHistory_Unit;

rule "PhenotypeD Rule"
    dialect "java"
    when
    //not AATD, exacerbations per year >= 2, time between exacerbations < 4, mixed_asthma = FALSE, cough = TRUE, CHRONIC_EXPECT = TRUE
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), signsAndSymptoms.getExacerbationCount()>=2, signsAndSymptoms.getTimeBetweenExacerbations()<4, !signsAndSymptoms.isMixed_asthma(), signsAndSymptoms.getCough(), signsAndSymptoms.getChronicExpectoration()]
    then
        modify ($MedicalHistory) {setPhenotype("D")}
end

rule "PhenotypeC Rule"
    dialect "java"
    when
    //not AATD, exacerbations per year >= 2, time between exacerbations < 4, mixed_asthma = FALSE, cough = FALSE, CHRONIC_EXPECT = FALSE
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), signsAndSymptoms.getExacerbationCount()>=2, signsAndSymptoms.getTimeBetweenExacerbations()<4, !signsAndSymptoms.isMixed_asthma(), !signsAndSymptoms.getCough(), !signsAndSymptoms.getChronicExpectoration()]
    then
        modify ($MedicalHistory) {setPhenotype("C")}
end

rule "PhenotypeB Rule 1"
    dialect "java"
    when
    //not AATD, exacerbations per year >= 2, time between exacerbations >=4, mixed_asthma = TRUE
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), signsAndSymptoms.getExacerbationCount()>=2, signsAndSymptoms.getTimeBetweenExacerbations()>=4, signsAndSymptoms.isMixed_asthma()]
    then
        modify ($MedicalHistory) {setPhenotype("B")}
end

rule "PhenotypeA Rule"
    dialect "java"
    when
    //not AATD, exacerbations per year <2 and mixed_asthma = FALSE and cough=TRUE, chronicExpect = TRUE
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), signsAndSymptoms.getExacerbationCount()<2, !signsAndSymptoms.isMixed_asthma(), signsAndSymptoms.getCough(), signsAndSymptoms.getChronicExpectoration()]
    then
        modify ($MedicalHistory) {setPhenotype("A")}
end

rule "PhenotypeB Rule 2"
    dialect "java"
    when
    //not AATD, exacerbations per year <2 and mixed_asthma = TRUE
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), signsAndSymptoms.getExacerbationCount()<2, signsAndSymptoms.isMixed_asthma()]
    then
        modify ($MedicalHistory) {setPhenotype("B")}
end

rule "AATD_Pheno"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.isAatd()]
    then 
        modify ($MedicalHistory) {setPhenotype("AATD")}
end
