/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package entities;

unit MedicalHistory_Unit;

rule "Severity 1 Rule" 
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getBodex()>=0,signsAndSymptoms.getBodex()<3]
    then 
        modify ($MedicalHistory) {setSeverityLevel(1)}
end
rule "Severity 2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getBodex()>2,signsAndSymptoms.getBodex()<5]
    then 
        modify ($MedicalHistory) {setSeverityLevel(2)}
end
rule "Severity 3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getBodex()>4,signsAndSymptoms.getBodex()<7]
    then 
        modify ($MedicalHistory) {setSeverityLevel(3)}
end
rule "Severity 4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getBodex()>=7]
    then 
        modify ($MedicalHistory) {setSeverityLevel(4)}
end

rule "COPD Assessment Test Severity 1 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getCOPDScore()>=0, signsAndSymptoms.getCOPDScore()<=10]
    then 
        modify ($MedicalHistory) {setSeverityLevel(1)}
end
rule "COPD Assessment Test Severity 2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getCOPDScore()>=0, signsAndSymptoms.getCOPDScore()>10,signsAndSymptoms.getCOPDScore()<21]
    then 
        modify ($MedicalHistory) {setSeverityLevel(2)}
end
rule "COPD Assessment Test Severity 3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getCOPDScore()>=0, signsAndSymptoms.getCOPDScore()>20,signsAndSymptoms.getCOPDScore()<31]
    then 
        modify ($MedicalHistory) {setSeverityLevel(3)}
end
rule "COPD Assessment Test Severity 4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.getCOPDScore()>=0, signsAndSymptoms.getCOPDScore()>30]
    then 
        modify ($MedicalHistory) {setSeverityLevel(4)}
end
