/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")}
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package entities;

unit MedicalHistory_Unit;

rule "PhenotypeA Severity1 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'A', severityLevel == 1]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("SABA / SAMA or LAMA / LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeA Severity2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'A', severityLevel == 2]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA / LABA or LAMA + LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeA Severity3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'A', severityLevel == 3]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeA Severity4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'A', severityLevel == 4]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA or LAMA + LABA + Teofiline")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeB Severity1 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'B', severityLevel == 1]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LABA + ICS")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeB Severity2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'B', severityLevel == 2]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LABA + ICS")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeB Severity3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'B', severityLevel == 3]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + ICS")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeB Severity4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'B', severityLevel == 4]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + ICS, Consider adding Teofiline/PDE4 with expectoration")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeC Severity1 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'C', severityLevel == 1]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA / LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeC Severity2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'C', severityLevel == 2]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("(LAMA / LABA) + ICS or LAMA + LABA or LAMA/LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeC Severity3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'C', severityLevel == 3]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + ICS")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeC Severity4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'C', severityLevel == 4]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + ICS, Consider adding Teofiline")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeD Severity1 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'D', severityLevel == 1]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA / LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeD Severity2 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'D', severityLevel == 2]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("(LAMA / LABA) + (ICS / PDE4) or LAMA + LABA or  LAMA / LABA")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeD Severity3 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'D', severityLevel == 3]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + (ICS / PDE4) or (LAMA / LABA) + ICS + PDE4, and consider adding Carbocisteine")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "PhenotypeD Severity4 Rule"
    dialect "java"
    when
        $MedicalHistory: /mHist [!signsAndSymptoms.isAatd(), phenotype == 'D', severityLevel == 4]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("LAMA + LABA + (ICS / PDE4) or LAMA + LABA + ICS + PDE4, and consider adding Carbocisteine/Antibiotics")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(21)}
end

rule "HUH"
    dialect "java"
    when
        $MedicalHistory: /mHist [phenotype == "?"]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("Unknown COPD Phenotype - No treatment available")}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(0)}
end

rule "AATD"
    dialect "java"
    when
        $MedicalHistory: /mHist [signsAndSymptoms.isAatd()]
    then 
        modify ($MedicalHistory) {setSuggestedTreatment("Alpha-1-Antitrypsin (AAT) therapy")}
        modify ($MedicalHistory) {setPhenotype("AATD")}
        modify ($MedicalHistory) {setSeverityLevel(0)}
        modify ($MedicalHistory){setBeginDate()}
        modify ($MedicalHistory){setDuration(0)}
end